### ISSUE TITLE
typo in the readme 

### ISSUE THREAD

**Issue by Fran-cois** [ychalier/leethan#1]
in the safari part you put 360000 instead of 3600 (for one hour) i guess ?

**Comment by ychalier** [comment]
Not even an issue. In the config file you write milliseconds. In the terminal you write seconds. Read the doc ffs!!!!! lmao

**Comment by Fran-cois** [comment]
that wasnt clear \o/

**Comment by ychalier** [comment]
Just praise the Lord and everything will be fine my son.
